#!/usr/bin/expect -f
spawn "/opt/software/jira/atlassian-jira-software-7.2.3-x64.bin"

expect "This will install JIRA Software 7.2.3 on your computer."
send "o\r"
expect "Choose the appropriate installation or upgrade option."
send "2\r"
expect "Where should JIRA Software be installed?"
send "\r"
expect "Default location for JIRA Software data"
send "\r"
expect "Configure which ports JIRA Software will use."
send "2\r"
expect "HTTP Port Number"
send "8091\r"
expect "Control Port Number"
send "8007\r"
expect "JIRA can be run in the background"
send "y\r"
expect "Details on where JIRA Software will be installed and the settings that will be used."
send "i\r"
expect "Please wait a few moments while JIRA Software is configured."
send "y\r"
expect "Finishing installation ..."
send "exit\r"

